// Joshua Nunez
// Writes docs/reference.md from the code itself: the roles and permission matrix, every API route, every MCP tool and
// plan action, the database tables and the migrations. A test checks the file is current, so it cannot drift.
// Run: node scripts/gen-docs.js
const fs = require('fs');
const path = require('path');

function build() {
  const { openDb } = require('../server/db');
  const perms = require('../server/services/permissions');
  const { TOOLS } = require('../server/mcp');
  const plans = require('../server/services/aiplans');
  const apiRouter = require('../server/routes/api');
  const db = openDb(':memory:');
  const out = [];
  const line = (s = '') => out.push(s);

  line('# Reference (generated)');
  line();
  line('Generated by `node scripts/gen-docs.js` from the code. Do not edit by hand; a test fails when this file is out of date.');
  line();

  line('## Roles and permissions');
  line();
  line(`Roles, highest first: ${[...perms.ROLES].sort((a, b) => perms.RANK[b] - perms.RANK[a]).join(', ')}. Every permission is checked on the server first; the screens only hide what the server would refuse.`);
  line();
  line('| Permission | ' + perms.ROLES.map((r) => r[0].toUpperCase() + r.slice(1)).join(' | ') + ' |');
  line('|---|' + perms.ROLES.map(() => ':-:').join('|') + '|');
  for (const action of Object.keys(perms.ACTIONS).sort()) line(`| \`${action}\` | ` + perms.ROLES.map((r) => (perms.can(r, action) ? 'yes' : '')).join(' | ') + ' |');
  line();

  line('## API routes');
  line();
  line('All under `/api`, JSON, with a session cookie and a CSRF token header on changes.');
  line();
  const router = apiRouter(db);
  const routes = [];
  for (const layer of router.stack) if (layer.route) for (const method of Object.keys(layer.route.methods)) routes.push(`${method.toUpperCase()} ${layer.route.path}`);
  for (const r of [...new Set(routes)].sort((a, b) => a.split(' ')[1].localeCompare(b.split(' ')[1]) || a.localeCompare(b))) line(`- \`${r}\``);
  line();

  line('## MCP tools');
  line();
  line('At `/mcp`, with an `aos_` API key or an OAuth connection. Read tools work for every key. Write tools exist only for keys set to propose or direct; they become plans (see below).');
  line();
  line('| Tool | Kind | What it does |');
  line('|---|---|---|');
  for (const t of TOOLS) line(`| \`${t.name}\` | ${t.write ? 'write (plan)' : 'read'} | ${String(t.description).replace(/\s+/g, ' ').replace(/\|/g, '/').replace(/ With a key that asks first.*$/, '')} |`);
  line();

  line('## Plan actions (what an AI may change)');
  line();
  line(`A plan is up to ${plans.MAX_STEPS} steps in one transaction. These are all the actions; there is no delete, and nothing about members, passwords, keys or settings.`);
  line();
  for (const a of Object.keys(plans.ACTIONS).sort()) line(`- \`${a}\``);
  line();

  line('## Database tables');
  line();
  const tables = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name != 'schema_migrations' ORDER BY name").all();
  for (const { name } of tables) {
    const cols = db.prepare(`PRAGMA table_info(${name})`).all().map((c) => c.name);
    line(`- \`${name}\`: ${cols.join(', ')}`);
  }
  line();

  line('## Migrations');
  line();
  const dir = path.resolve(__dirname, '..', 'database', 'migrations');
  for (const f of fs.readdirSync(dir).filter((x) => x.endsWith('.sql')).sort()) line(`- \`${f}\``);
  line();
  return out.join('\n');
}

if (require.main === module) {
  fs.writeFileSync(path.resolve(__dirname, '..', 'docs', 'reference.md'), build());
  console.log('docs/reference.md written');
}
module.exports = { build };
